alias ls="exa"
alias tree="exa --tree"
alias ll="ls -lahFG"
alias l="ls"
alias gti="git"
alias gits="git status"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias cat="bat -p"
alias grep="rg"
alias vim="nvim"
alias tf="terraform"
alias dc="docker-compose"
