alias l="exa"
alias ll="exa -laH@"
alias gti="git"
alias gits="git status"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias cat="bat -p"
alias grep="rg"
alias vim="nvim"
alias tf="terraform"
alias dc="docker-compose"
